FORMAT: 1A
HOST: http://www.darkroomlocator.com/api

# darkroomlocator
*RESTful* API of darkroomlocator webapp

# Group User 
User related resources of the **darkroomlocator API**

## /login
### POST

Login *public*

+ Request (application/json)

    + Header

            lang: it
    
    + Body
    
            {
                "username": "sadmaster",
                "password": "sandrino"
            } 

+ Response 200 (application/json)

        {
          "sbe": [
            {
              "codVettore": 1,
              "codSbe": 1,
              "descrizioneSbe": "Biglietto Integrato Piemonte",
              "descrizioneVettore": "TRENITALIA"
            }
          ],
          "identifySession": "MTAuMTAwLjEzMy4xODB8fFRQTC1BTVYtMDU3NTMxfHwxNDEyNjg3NjQyNDE2",
          "resultCode": 200,
          "resultDesc": "OK",
          "lang": "it"
        }
