FORMAT: 1A
HOST: http://www.darkroomlocator.com/api

# darkroomlocator
*RESTful* API of darkroomlocator webapp

# Group User 
User related resources of the **darkroomlocator API**

## /login
### POST

Login, create session and obtain authKey to sign private method

*public method*

+ Request (application/json)

    + Header

            lang: it
    
    + Body
    
            {
                "username": "utente",
                "password": "prova"
            } 

+ Response 200 (application/json)

        {
          "success": true,
          "user": {
            "__v": 0,
            "_id": "5265424b7a0ea20000000002",
            "email": "provadark@gmail.com",
            "first_name": "Mario",
            "last_name": "Rossi",
            "username": "utente",
            "verified": true,
            "auth": {
              "activate_date": "2013-10-21T15:04:24.000Z",
              "authkey": "33f5f3e0-53aa-11e4-b02a-5d71a1137a92",
              "ipaddress": "5.175.48.17",
              "login_date": "2014-10-14T13:58:40.000Z"
            },
            "registration_date": "2013-10-21T12:38:22.000Z"
          }
        }
